### ISSUE TITLE
Block indicator bubble for new Notifications

### ISSUE THREAD

**Issue by katrinleinweber** [brunolemos/simplified-twitter#7]
Hello & thanks for publishing this add-on :-)

Would it be possible to selectively block that little annoyance? Since notifications include retweets & likes, no active review is really necessary, so the indicator bubble (green, at the bell icon in the example below) could be counted as click-baiting.

The CSS selector and class IDs are randomized, unfortunately: `div.r-b5skir:nth-child(2)`, but maybe the combination of the other `div` attributes can be used to block it?

### Example

![Screen Shot 2020-02-26 at 06 04 30](https://user-images.githubusercontent.com/9948149/75313740-01e24e80-585e-11ea-9b4b-c4e33c238b28.png)

```
<div dir="auto" aria-label="8 unread items" aria-live="polite"
class="css-901oao r-1awozwy r-b5skir r-f6ebdl r-sdzlij r-1phboty r-rs99b7 r-1tjplnt r-jwli3a r-6koalj r-1q142lx r-1qd0xha r-1gkfh8e r-16dba41 r-50lct3 r-1777fci r-ad9z0x r-1b8eohn r-u8s1d r-kquydp r-1m4drjs r-3s2u2q r-qvutc0"
style="color: rgb(23, 191, 99);">
8
</div>
```

**Comment by brunolemos** [comment]
Hi, thanks for your suggestion!

Simplified Twitter actually has zero custom CSS. The only thing it does is add 3 javascript line to make Twitter think the window is smaller. I don't plan add custom css since that could stop working anytime and each person would suggest a different change.

>Why is this better than the alternatives?
>They all make the same mistake: Mess with CSS

>At the new twitter the class names are random and dynamic (e.g.: .css-1dbjc4n instead of .my-class->name). Extensions that depend on class names will break at any time.

>This extension tricks Twitter to think the window is smaller, and Twitter adjusts everything by itself. We >don't need to apply hacky styles, twitter is already responsive by default.

If you need custom styles, I recommend using some other extension for that, maybe Stylish https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe
